#ifndef __LIBRS232_VERSION_H__
#define __LIBRS232_VERSION_H__

#define RS232_VERSION_MAJOR ${LIB_VERSION_MAJOR}
#define RS232_VERSION_MINOR ${LIB_VERSION_MINOR}
#define RS232_VERSION_PATCH ${LIB_VERSION_PATCH}
#define RS232_VERSION "${LIBRARY_VERSION}"
#define RS232_VERSION_LUA RS232_VERSION ".${LIB_VERSION_LUA}"

#endif
