option(WITH_LOGGING "Build with logging support" ON)
option(WITH_DEBUG_LOGGING "Build with debug logging support" OFF)
option(UNIT_TESTING "Build and run unit tests" OFF)
option(LUA_BINDINGS "Build with Lua bindings" OFF)
option(LUA_RS232_STATIC "Build Lua bindings with librs232 compiled statically" OFF)
